version: 2.1
#orbs:
#  codecov: codecov/codecov@1.0.2
jobs:
  unit-test:
    docker:
      - image: 'circleci/golang:latest'
    steps:
      - checkout
      - run:
          # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Unit Test
          command: |
            go test -tags unit ./...
#  build:
#    machine: true
#    steps:
#      - checkout
#      - run:
#          name: Build
#          command: |
#            docker build -t bockyanggoh/auto-porter-go:alpha .
#      - run:
#          name: Push
#          command: |
#            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
#            docker push bockyanggoh/auto-porter-go
#workflows:
#  version: 2
#  build:
#    jobs:
#      - test
#      - build:
#          requires:
#            - test
#          context: dockerhub